name: yantra_smart_home_automation
description: "Advanced Smart Home Automation with Supabase & IoT"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2
  
  # Supabase
  supabase_flutter: ^2.9.1
  
  # MQTT (AWS IoT Core)
  mqtt_client: ^10.10.0
  
  # UI & Design
  flutter_colorpicker: ^1.1.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  
  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  
  # Networking & HTTP
  http: ^1.4.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  
  # Device & Permissions
  wifi_iot: ^0.3.19+2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  
  # Date & Time
  intl: ^0.20.2
  timezone: ^0.10.1
  
  # Local Storage & Preferences
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  
  # Utils
  uuid: ^4.5.1
  collection: ^1.19.1
  rxdart: ^0.28.0
  equatable: ^2.0.7
  
  # Development & Debugging
  logger: ^2.6.0
  
  # Security
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    # Secrets (for MQTT)
    - assets/secrets/
    
    # Device Icons
    - assets/icons/devices/
    - assets/icons/rooms/
    - assets/icons/general/
    
    # Images
    - assets/images/
    - assets/logo.png
    
    # Animations
    - assets/animations/
    
    # Original device icons (maintaining compatibility)
    - assets/light-bulb.png
    - assets/air-conditioner.png
    - assets/blinds.png
    - assets/fan.png
    - assets/geyser.png
    - assets/refrigerator.png
    - assets/led-strip.png
    - assets/light.png
    - assets/power-socket.png
    - assets/rgb.png
    - assets/room.png
    - assets/washing-machine.png
    - assets/table_fan.png
    - assets/chandlier.png
    - assets/cooling-fan.png
    - assets/food.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700